In [ ]:
import pyfits as pf

In [ ]:
from IPython.core.display import HTML
HTML("<style>.container { width:90% !important; }</style>")

In [ ]:
import os
import numpy as np
import lsst.daf.persistence as dafPersist
import lsst.afw.display.ds9 as ds9
import lsst.afw.geom as afwGeom
import lsst.afw.geom.ellipses as afwEllipse
import lsst.afw.cameraGeom as cameraGeom

butler = dafPersist.Butler('/nfs/lsst2/photocalData/data/decam/rerun/4')

In [ ]:
dataId = dict(visit=496473, ccdnum=20)

icSrcCat = butler.get("icSrc", dataId)


In [13]:
# icSrcCat.schema
print icSrcCat

<lsst.afw.table.tableLib.SourceCatalog; proxy of <Swig Object of type 'lsst::afw::table::SortedCatalogT< lsst::afw::table::SourceRecord > *' at 0x7f5a05c745a0> >


In [31]:
for _ in icSrcCat.schema.getNames():
    print _

apcorr_base_CircularApertureFlux_17_0_used
apcorr_base_GaussianFlux_used
apcorr_base_PsfFlux_used
base_CircularApertureFlux_12_0_flag
base_CircularApertureFlux_12_0_flag_apertureTruncated
base_CircularApertureFlux_12_0_flux
base_CircularApertureFlux_12_0_fluxSigma
base_CircularApertureFlux_17_0_flag
base_CircularApertureFlux_17_0_flag_apertureTruncated
base_CircularApertureFlux_17_0_flux
base_CircularApertureFlux_17_0_fluxSigma
base_CircularApertureFlux_25_0_flag
base_CircularApertureFlux_25_0_flag_apertureTruncated
base_CircularApertureFlux_25_0_flux
base_CircularApertureFlux_25_0_fluxSigma
base_CircularApertureFlux_35_0_flag
base_CircularApertureFlux_35_0_flag_apertureTruncated
base_CircularApertureFlux_35_0_flux
base_CircularApertureFlux_35_0_fluxSigma
base_CircularApertureFlux_3_0_flag
base_CircularApertureFlux_3_0_flag_apertureTruncated
base_CircularApertureFlux_3_0_flag_sincCoeffsTruncated
base_CircularApertureFlux_3_0_flux
base_CircularApertureFlux_3_0_fluxSigma
base_CircularApe

In [36]:
from lsst.afw.table import *
test_schema = Schema()
k1 = test_schema.addField("f1", type=int, doc="doc for f1")
k2 = test_schema.addField("f2", type=numpy.float32, doc="doc for f2", units="units for f2")
k3 = test_schema.addField("f3", type="ArrayD", doc="doc for f3", units="units for f2", size=5)
catalog = BaseCatalog(test_schema)
for i in (1, 2, 3):
    record = catalog.addNew()
    record.set(k1, i)
    record.set(k2, i * 3.14)
    record[k3] = numpy.random.rand(5) + i # ndarray::Array == numpy.ndarray in Python
print catalog[k1]
print
print catalog[k2]
print
print catalog[k3]   # in Python, can access columns directly from the catalog

[1 2 3]

[ 3.1400001   6.28000021  9.42000008]

[[ 1.67692687  1.91912027  1.2227108   1.48059863  1.26257608]
 [ 2.03789659  2.85187468  2.37584135  2.2561221   2.56024498]
 [ 3.48816453  3.16739847  3.1739747   3.33241432  3.36337274]]
